import { SessionGateError, type SessionGateValidator, type AuditLogger } from './types.js';

/**
 * Enforces Design Choice D2:
 * Rejects any Factor 1 request immediately if the user does not have an active, unexpired PartialAuthSession.
 *
 * @param sessionToken - Ephemeral partial session token generated by Senadi's session manager upon Factor 2 completion
 * @param userId - ID of the user requesting Factor 1
 * @param validator - SessionGateValidator implementation from Senadi's server module
 * @param auditLogger - Optional AuditLogger from Hasini's security module to log blocked gate attempts
 * @throws {SessionGateError} If session token is missing, expired, invalid, or belongs to a different user
 */
export async function assertSessionGateActive(
  sessionToken: string | undefined | null,
  userId: string,
  validator: SessionGateValidator,
  auditLogger?: AuditLogger,
  ceremony: 'REGISTRATION' | 'AUTHENTICATION' = 'AUTHENTICATION',
  clientContext?: { ipAddress?: string; userAgent?: string }
): Promise<void> {
  if (!sessionToken || sessionToken.trim() === '') {
    if (auditLogger) {
      await auditLogger.logAttempt({
        userId,
        factor: 'FACTOR_1_WEBAUTHN',
        ceremony,
        outcome: 'BLOCKED_SESSION_GATE',
        reason: 'MISSING_SESSION_TOKEN',
        ipAddress: clientContext?.ipAddress,
        userAgent: clientContext?.userAgent,
        timestamp: new Date(),
      }).catch(() => {
        // Logging failure should not suppress primary security rejection
      });
    }
    throw new SessionGateError('MISSING_SESSION_TOKEN', userId);
  }

  const validationResult = await validator.validatePartialSession(sessionToken, userId);

  if (!validationResult.isValid) {
    const reason = validationResult.reason || 'INVALID_PARTIAL_SESSION';

    if (auditLogger) {
      await auditLogger.logAttempt({
        userId,
        factor: 'FACTOR_1_WEBAUTHN',
        ceremony,
        outcome: 'BLOCKED_SESSION_GATE',
        reason,
        ipAddress: clientContext?.ipAddress,
        userAgent: clientContext?.userAgent,
        timestamp: new Date(),
      }).catch(() => {
        // Fail-safe audit logging
      });
    }

    throw new SessionGateError(reason, userId);
  }
}
